const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const menu=$('#menu'),nav=$('#nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});$$('#nav a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')});
const toast=$('#toast');function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove('show'),2400)};$$('[data-toast]').forEach(a=>a.onclick=e=>{e.preventDefault();showToast(a.dataset.toast)});
const qs=[['۳ سیب داریم و ۲ سیب دیگر اضافه می‌کنیم. چند سیب داریم؟',['۴','۵','۶'],'۵'],['کدام گزینه یک رنگ است؟',['بنفش','کتاب','پروانه'],'بنفش'],['۵ ستاره داریم و ۱ ستاره هدیه می‌گیریم. چند ستاره داریم؟',['۶','۷','۴'],'۶']];let i=0,score=0;const q=$('#question'),opts=$('#options'),msg=$('#message'),next=$('#next'),scoreEl=$('#score'),bar=$('#bar');const fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
function render(){q.textContent=qs[i][0];opts.innerHTML=qs[i][1].map(x=>`<button data-a="${x}">${x}</button>`).join('');msg.textContent='یک گزینه را انتخاب کن 🌸';next.classList.add('hidden');bar.style.width=`${(i+1)/qs.length*100}%`;$$('#options button').forEach(b=>b.onclick=()=>answer(b))}function answer(b){const all=$$('#options button'),right=qs[i][2];all.forEach(x=>x.disabled=true);if(b.dataset.a===right){b.classList.add('correct');score+=10;scoreEl.textContent=fa(score);msg.textContent='آفرین! پروانه یک قدم جلو رفت 🦋✨'}else{b.classList.add('wrong');all.find(x=>x.dataset.a===right)?.classList.add('correct');msg.textContent='اشکالی ندارد؛ یک بار دیگر فکر کن 🌱'}next.classList.remove('hidden')}
next.onclick=()=>{i++;if(i>=qs.length){q.textContent='گنجینه پیدا شد! 🏆';opts.innerHTML='';msg.textContent=`امتیاز نهایی تو ${fa(score)} است. این فقط شروع ماجراجویی الهه بود.`;next.textContent='شروع دوباره';next.onclick=()=>{i=0;score=0;scoreEl.textContent='۰';next.textContent='سؤال بعدی';next.onclick=advance;render()};bar.style.width='100%'}else render()};function advance(){i++;if(i>=qs.length){q.textContent='گنجینه پیدا شد! 🏆';opts.innerHTML='';msg.textContent=`امتیاز نهایی تو ${fa(score)} است.`;next.textContent='شروع دوباره';next.onclick=()=>{i=0;score=0;scoreEl.textContent='۰';next.textContent='سؤال بعدی';next.onclick=advance;render()};return}render()};render();
const rev=$$('.reveal');if('IntersectionObserver'in window){const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');ob.unobserve(e.target)}}),{threshold:.08});rev.forEach(x=>ob.observe(x))}else rev.forEach(x=>x.classList.add('show'));
const links=$$('#nav a');if('IntersectionObserver'in window){const so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-25% 0px -65%'});['school','learn','game','mag','gallery','parents'].forEach(id=>{const x=document.getElementById(id);if(x)so.observe(x)})}
const top=$('#top');window.addEventListener('scroll',()=>top.classList.toggle('show',scrollY>500),{passive:true});top.onclick=()=>scrollTo({top:0,behavior:'smooth'});
