(()=>{
const DATA=window.ELAHA_ASSISTANT_DATA;if(!DATA)return;
const norm=s=>String(s||'').toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[ۀة]/g,'ه').replace(/[ًٌٍَُِّْ]/g,'').replace(/[ـ]/g,'').replace(/[\u200c\u200f]/g,' ').replace(/[؟?!.,،؛:()\[\]{}«»"']/g,' ').replace(/\s+/g,' ').trim();
const words=s=>norm(s).split(' ').filter(Boolean),stop=new Set(['من','می','را','رو','در','به','از','برای','که','این','آن','یه','یک','چطور','چگونه','لطفا','لطفاً','میشه','می‌شود','هست','است','درباره','تو','و','یا']);
const clean=s=>words(s).filter(w=>!stop.has(w));
const edit=(a,b)=>{if(a===b)return 1;if(!a||!b)return 0;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let c=[i];for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=c}return 1-Math.min(p[b.length],Math.max(a.length,b.length))/Math.max(a.length,b.length)};
const score=(q,k)=>{const a=clean(q),b=clean(k);if(!a.length||!b.length)return 0;let hit=0;for(const x of a){if(b.includes(x)){hit+=1;continue}if(b.some(y=>Math.max(x.length,y.length)>3&&edit(x,y)>=.72))hit+=.7}let s=hit/Math.max(a.length,b.length),nq=norm(q),nk=norm(k);if(nq.includes(nk))s+=.45;for(const x of b)if(nq.includes(x))s+=.06;return Math.min(s,1)};
const getBest=q=>{let best=null,bs=0;for(const fact of DATA.facts)for(const key of fact.keys){const s=score(q,key);if(s>bs){bs=s;best=fact}}return {fact:best,score:bs}};
const direct={آدرس:'address',نشانی:'address',کجا:'address',بازی:'games',سرگرمی:'games',ثبت:'account',ورود:'account',شهریه:'fees',هزینه:'fees',تلفن:'contact',تماس:'contact',ساعت:'hours',والدین:'parents',اولیا:'parents',یادگیری:'learning',گالری:'gallery',مجله:'magazine',اخبار:'magazine',لوگو:'logo',پذیرش:'admission'};
function enhanceNav(){const head=document.querySelector('header.header'),nav=head?.querySelector('nav');if(!head||!nav)return;document.querySelectorAll('.brand img').forEach(i=>{i.src='assets/logo-official.svg';i.alt='لوگوی رسمی دبستان و پیش‌دبستانی دخترانه الهه'});if(document.querySelector('#elahe-mobile-menu'))return;const b=document.createElement('button');b.id='elahe-mobile-menu';b.className='menu';b.type='button';b.textContent='☰';b.setAttribute('aria-label','باز کردن منو');b.setAttribute('aria-expanded','false');head.appendChild(b);b.onclick=()=>{const o=nav.classList.toggle('elahe-nav-open');b.setAttribute('aria-expanded',String(o));b.textContent=o?'×':'☰'};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('elahe-nav-open');b.setAttribute('aria-expanded','false');b.textContent='☰'}));}
function loadCss(){if(document.querySelector('link[data-elahe-assistant]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='assistant.css';l.dataset.elaheAssistant='1';document.head.appendChild(l)}
function answer(q,history){const n=norm(q);if(!n)return {text:'یک سؤال کوتاه بنویس تا دقیق کمکت کنم 🌸',links:[]};
if(/^(سلام|درود|سلاممم|وقت بخیر|خوبی|چطوری|چه خبر)$/.test(n))return {text:'سلام! من «یارِ الهه» هستم 🦋🤍\nدرباره مدرسه و بخش‌های سایت از من بپرس. من فقط به اطلاعات ثبت‌شده تکیه می‌کنم و چیزی را حدس نمی‌زنم.',links:[['معرفی مدرسه','#school'],['بازی‌ها','#game'],['والدین','#parents']]};
if(/^(ممنون|مرسی|تشکر|خیلی ممنون)/.test(n))return {text:'خواهش می‌کنم 🌷',links:[]};
if(/^(خداحافظ|فعلا|فعلاً|بای)$/.test(n))return {text:'فعلاً 🌸 به دنیای الهه دوباره سر بزن.',links:[]};
if(n.includes('آدرس')||n.includes('نشانی')||n.includes('کجا')){const f=DATA.facts.find(x=>x.id==='address');if(f)return {text:f.answer,links:f.links||[]}}
if((n.includes('پایه')||n.includes('کلاس'))&&(n.includes('چه')||n.includes('چند')||n.includes('دارد')))return {text:'طبق اطلاعات فعلی، مدرسه یک دبستان و پیش‌دبستانی دخترانه است؛ جزئیات پایه‌ها هنوز وارد نشده و بعداً با اطلاعات رسمی تکمیل می‌شود.',links:[['مدرسه ما','#school']]};
for(const t of Object.keys(direct))if(n.includes(t)){const f=DATA.facts.find(x=>x.id===direct[t]);if(f)return {text:f.answer,links:f.links||[]}}
const best=getBest(q);if(best.fact&&best.score>=.34)return {text:best.fact.answer,links:best.fact.links||[],score:best.score,fact:best.fact.id};
if(history.lastFact&&/^(اون|آن|این|همین|پس|یعنی|خب)\b/.test(n))return {text:`اگر منظورت ادامه‌ی «${history.lastFact}» است، سؤال را کمی کامل‌تر بنویس تا دقیق جواب بدهم. 🌱`,links:[]};
return {text:DATA.fallback[Math.floor(Math.random()*DATA.fallback.length)],links:[]}}
function mount(){if(document.getElementById('elaha-assistant'))return;loadCss();enhanceNav();const root=document.createElement('div');root.id='elaha-assistant';root.innerHTML=`<button class="ea-launch" aria-label="باز کردن دستیار یار الهه"><img src="assets/logo-official.svg" alt=""><span class="ea-badge">یار الهه</span><i>✦</i></button><section class="ea-panel" role="dialog" aria-label="دستیار یار الهه" aria-hidden="true"><header><div class="ea-head-brand"><img src="assets/logo-official.svg" alt=""><div><strong>یارِ الهه 🦋</strong><small>دستیار آفلاین مدرسه</small></div></div><button class="ea-close" aria-label="بستن">×</button></header><div class="ea-note">بدون API؛ پرسش‌ها به هیچ سرویس بیرونی ارسال نمی‌شوند. پاسخ‌ها از دانش‌نامه‌ی همین سایت می‌آیند.</div><div class="ea-messages" aria-live="polite"></div><div class="ea-suggest"><button>آدرس مدرسه؟</button><button>چه بازی‌هایی دارید؟</button><button>ثبت‌نام چطور است؟</button><button>شماره تماس دارید؟</button></div><form class="ea-form"><input autocomplete="off" placeholder="مثلاً: ساعت مدرسه چه موقع است؟" aria-label="سؤال شما"><button aria-label="ارسال">➤</button></form><div class="ea-status">پاسخ‌ها محافظه‌کارانه و بر اساس اطلاعات ثبت‌شده‌اند.</div></section>`;document.body.appendChild(root);const p=root.querySelector('.ea-panel'),l=root.querySelector('.ea-launch'),c=root.querySelector('.ea-close'),m=root.querySelector('.ea-messages'),inp=root.querySelector('input'),form=root.querySelector('form');let history={lastFact:''};
const add=(who,text,links=[])=>{const row=document.createElement('div');row.className=`ea-msg ${who}`;const b=document.createElement('div');b.textContent=text;row.appendChild(b);if(links.length){const nav=document.createElement('div');nav.className='ea-links';links.forEach(([label,href])=>{const a=document.createElement('a');a.href=href;a.textContent=label;a.onclick=()=>p.classList.remove('open');nav.appendChild(a)});row.appendChild(nav)}m.appendChild(row);m.scrollTop=m.scrollHeight};
const open=()=>{p.classList.add('open');p.setAttribute('aria-hidden','false');setTimeout(()=>inp.focus(),100)},close=()=>{p.classList.remove('open');p.setAttribute('aria-hidden','true')};l.onclick=()=>p.classList.contains('open')?close():open();c.onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});add('bot','سلام! من یارِ الهه هستم 🌸\nدرباره مدرسه، بازی‌ها، یادگیری، گالری، مجله یا والدین سؤال بپرس.');root.querySelectorAll('.ea-suggest button').forEach(b=>b.onclick=()=>{inp.value=b.textContent;form.requestSubmit()});form.onsubmit=e=>{e.preventDefault();const q=inp.value.trim();if(!q)return;add('user',q);inp.value='';const r=answer(q,history);if(r.fact)history.lastFact=r.fact;setTimeout(()=>add('bot',r.text,r.links),120)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();})();